import type { Vendor, VendorPrice } from "@/lib/types";

export const officialVendorSeed: Vendor[] = [
  {
    id: "vendor-convent-garden-donostia",
    name: "Convent Garden",
    category: "localizacion",
    region: "Gipuzkoa",
    province: "Gipuzkoa",
    city: "Donostia-San Sebastian",
    serviceArea: "Gipuzkoa y Pais Vasco",
    phone: "",
    email: "",
    website: "https://conventgarden.es/",
    contactUrl: "https://conventgarden.es/",
    sourceUrl: "https://conventgarden.es/",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Convent%20Garden%20Donostia",
    capacity: 180,
    styleTags: ["urbano", "historico", "jardin", "industrial"],
    languages: ["castellano", "euskera"],
    availabilityType: "local",
    packages: [{ name: "espacio" }, { name: "evento completo" }],
    priceFrom: 3000,
    priceRange: "Consultar",
    priceConfidence: "baja",
    reliability: 8,
    responseTimeHours: 24,
    previousExperience: 6,
    qualityScore: 8.7,
    commissionFree: true,
    notes: "Espacio para bodas y eventos en Donostia. Fuente inicial pendiente de validacion comercial directa.",
    reviewsSummary: "Pendiente de revision manual en Google Places.",
    notesInternal: "Validar capacidad, exclusividad, condiciones de montaje y horarios.",
    status: "reviewed",
    lastCheckedAt: "2026-07-06",
    lat: 43.321,
    lng: -1.982
  },
  {
    id: "vendor-restaurante-arraiz-bilbao",
    name: "Restaurante Arraiz",
    category: "localizacion",
    region: "Vizcaya",
    province: "Bizkaia",
    city: "Bilbao",
    serviceArea: "Bilbao y Bizkaia",
    phone: "",
    email: "",
    website: "https://restaurantearraiz.com/eventos-bodas/",
    contactUrl: "https://restaurantearraiz.com/eventos-bodas/",
    sourceUrl: "https://restaurantearraiz.com/eventos-bodas/",
    instagramUrl: "https://www.instagram.com/restaurantearraiz/",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Restaurante%20Arraiz%20Bilbao",
    capacity: 160,
    styleTags: ["naturaleza", "montana", "gastronomico", "jardin"],
    languages: ["castellano", "euskera"],
    availabilityType: "local",
    packages: [{ name: "banquete" }, { name: "ceremonia" }, { name: "espacio" }],
    priceFrom: 165,
    priceRange: "Menu desde 165 EUR aprox.",
    priceConfidence: "media",
    reliability: 8.5,
    responseTimeHours: 24,
    previousExperience: 8,
    qualityScore: 8.8,
    commissionFree: true,
    notes: "Restaurante y espacio de boda en entorno natural cerca de Bilbao, con jardin y banquete.",
    reviewsSummary: "Revisar opiniones actuales antes de proponerlo a pareja.",
    notesInternal: "Puede encajar para parejas que buscan naturaleza sin salir del entorno Bilbao.",
    status: "reviewed",
    lastCheckedAt: "2026-07-06",
    lat: 43.246,
    lng: -2.983
  },
  {
    id: "vendor-palacio-horkasitas-bizkaia",
    name: "Palacio Horkasitas",
    category: "localizacion",
    region: "Vizcaya",
    province: "Bizkaia",
    city: "Artzentales",
    serviceArea: "Bizkaia, Cantabria oriental y Pais Vasco",
    phone: "686372210",
    email: "info@palaciohorkasitas.com",
    website: "https://palaciohorkasitas.com/",
    contactUrl: "https://palaciohorkasitas.com/",
    sourceUrl: "https://palaciohorkasitas.com/",
    instagramUrl: "https://www.instagram.com/palaciohorkasitas/",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Palacio%20Horkasitas%20Artzentales",
    capacity: 200,
    styleTags: ["palacio", "historico", "jardin", "exclusivo"],
    languages: ["castellano"],
    availabilityType: "local",
    packages: [{ name: "alquiler espacio" }, { name: "evento" }],
    priceFrom: 3000,
    priceRange: "3.000-3.200 EUR espacio aprox.",
    priceConfidence: "media",
    reliability: 8.6,
    responseTimeHours: 24,
    previousExperience: 7,
    qualityScore: 8.9,
    commissionFree: true,
    notes: "Palacete historico en Bizkaia orientado a bodas y eventos.",
    reviewsSummary: "Pendiente de comprobar disponibilidad y condiciones actualizadas.",
    notesInternal: "Buen candidato para bodas con estetica palacio/campo. Confirmar proveedores obligatorios.",
    status: "reviewed",
    lastCheckedAt: "2026-07-06",
    lat: 43.252,
    lng: -3.233
  },
  {
    id: "vendor-hotel-luze-san-sebastian",
    name: "Hotel Luze San Sebastian",
    category: "alojamiento",
    region: "Gipuzkoa",
    province: "Gipuzkoa",
    city: "Donostia-San Sebastian",
    serviceArea: "Donostia-San Sebastian",
    phone: "",
    email: "",
    website: "https://hotelluzesansebastian.es/",
    contactUrl: "https://hotelluzesansebastian.es/",
    sourceUrl: "https://hotelluzesansebastian.es/",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Hotel%20Luze%20San%20Sebastian",
    capacity: 120,
    styleTags: ["hotel", "belle epoque", "alojamiento", "urbano"],
    languages: ["castellano", "ingles"],
    availabilityType: "local",
    packages: [{ name: "alojamiento" }, { name: "habitaciones bloqueadas" }],
    priceFrom: 160,
    priceRange: "Consultar habitaciones",
    priceConfidence: "baja",
    reliability: 8.2,
    responseTimeHours: 24,
    previousExperience: 4,
    qualityScore: 8.4,
    commissionFree: true,
    notes: "Hotel en San Sebastian util para alojamiento de invitados y logistica urbana.",
    reviewsSummary: "Pendiente de revisar tarifas de grupo y politica de cancelacion.",
    notesInternal: "No asignar como lugar de celebracion inicial; usar como alojamiento cuando el proyecto avance.",
    status: "reviewed",
    lastCheckedAt: "2026-07-06",
    lat: 43.318,
    lng: -2.002
  },
  {
    id: "vendor-gaizka-corta-fotografia",
    name: "Gaizka Corta Fotografia",
    category: "fotografia",
    region: "Gipuzkoa",
    province: "Gipuzkoa",
    city: "Donostia-San Sebastian",
    serviceArea: "Gipuzkoa y desplazamientos",
    phone: "",
    email: "",
    website: "https://gcfotografia.es/",
    contactUrl: "https://gcfotografia.es/",
    sourceUrl: "https://gcfotografia.es/",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Gaizka%20Corta%20Fotografia%20San%20Sebastian",
    capacity: 250,
    styleTags: ["natural", "artistico", "documental", "pareja"],
    languages: ["castellano"],
    availabilityType: "se-desplaza",
    packages: [{ name: "reportaje completo" }, { name: "sesion pareja" }],
    priceFrom: 1800,
    priceRange: "Consultar reportaje",
    priceConfidence: "baja",
    reliability: 8.4,
    responseTimeHours: 24,
    previousExperience: 8,
    qualityScore: 8.7,
    commissionFree: true,
    notes: "Fotografo de bodas en San Sebastian con enfoque natural y artistico.",
    reviewsSummary: "Pendiente de revisar portfolio completo y disponibilidad.",
    notesInternal: "Solicitar galeria completa reciente antes de recomendar.",
    status: "reviewed",
    lastCheckedAt: "2026-07-06",
    lat: 43.318,
    lng: -1.981
  },
  {
    id: "vendor-larrea-prestatuak-catering",
    name: "Larrea Prestatuak",
    category: "restauracion",
    region: "Gipuzkoa",
    province: "Gipuzkoa",
    city: "",
    serviceArea: "Gipuzkoa",
    phone: "",
    email: "",
    website: "https://www.larreaprestatuak.com/catering-gipuzkoa.html",
    contactUrl: "https://www.larreaprestatuak.com/catering-gipuzkoa.html",
    sourceUrl: "https://www.larreaprestatuak.com/catering-gipuzkoa.html",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Larrea%20Prestatuak%20Gipuzkoa",
    capacity: 250,
    styleTags: ["catering", "familiar", "popular", "local"],
    languages: ["castellano", "euskera"],
    availabilityType: "local",
    packages: [{ name: "catering evento" }, { name: "celebracion familiar" }],
    priceFrom: 98,
    priceRange: "Consultar menu",
    priceConfidence: "baja",
    reliability: 8,
    responseTimeHours: 24,
    previousExperience: 5,
    qualityScore: 8,
    commissionFree: true,
    notes: "Catering para eventos y celebraciones en Gipuzkoa.",
    reviewsSummary: "Pendiente de validar menus de boda y condiciones de desplazamiento.",
    notesInternal: "Pedir dossier actualizado si se usa para boda formal.",
    status: "reviewed",
    lastCheckedAt: "2026-07-06",
    lat: 43.185,
    lng: -2.092
  },
  {
    id: "vendor-ona-catering",
    name: "Ona Catering",
    category: "restauracion",
    region: "Pais Vasco",
    province: "Gipuzkoa",
    city: "",
    serviceArea: "Pais Vasco",
    phone: "",
    email: "",
    website: "https://ona.catering/",
    contactUrl: "https://ona.catering/",
    sourceUrl: "https://ona.catering/",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Ona%20Catering%20Pais%20Vasco",
    capacity: 300,
    styleTags: ["catering", "gastronomico", "elegante", "evento"],
    languages: ["castellano", "euskera"],
    availabilityType: "se-desplaza",
    packages: [{ name: "boda" }, { name: "evento empresa" }],
    priceFrom: 120,
    priceRange: "Consultar menu",
    priceConfidence: "baja",
    reliability: 8,
    responseTimeHours: 24,
    previousExperience: 5,
    qualityScore: 8.2,
    commissionFree: true,
    notes: "Catering con servicio de bodas y eventos.",
    reviewsSummary: "Pendiente de contraste con resenas y propuesta actual.",
    notesInternal: "Validar radio de servicio y logistica de cocina in situ.",
    status: "reviewed",
    lastCheckedAt: "2026-07-06",
    lat: 43.22,
    lng: -2.12
  },
  {
    id: "vendor-mimiku-floristeria",
    name: "Mimiku",
    category: "floristeria",
    region: "Gipuzkoa",
    province: "Gipuzkoa",
    city: "Donostia-San Sebastian",
    serviceArea: "Donostia-San Sebastian y alrededores",
    phone: "",
    email: "",
    website: "https://www.mimiku.eus/",
    contactUrl: "https://www.mimiku.eus/",
    sourceUrl: "https://www.mimiku.eus/",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mimiku%20Floristeria%20Donostia",
    capacity: 180,
    styleTags: ["floral", "mimo", "natural", "decoracion"],
    languages: ["castellano", "euskera"],
    availabilityType: "local",
    packages: [{ name: "ramos" }, { name: "decoracion floral" }, { name: "bodas" }],
    priceFrom: 800,
    priceRange: "800-1.500 EUR aprox.",
    priceConfidence: "media",
    reliability: 8.3,
    responseTimeHours: 24,
    previousExperience: 6,
    qualityScore: 8.5,
    commissionFree: true,
    notes: "Floristeria de Donostia especializada en ramos, arreglos para bodas y decoracion para eventos.",
    reviewsSummary: "Pendiente de revision de portfolio de bodas reciente.",
    notesInternal: "Buena opcion para estetica natural y cercana. Confirmar montaje y desmontaje.",
    status: "reviewed",
    lastCheckedAt: "2026-07-06",
    lat: 43.314,
    lng: -1.982
  },
  {
    id: "vendor-villa-maria-luisa-floristeria",
    name: "Floristeria Villa Maria Luisa",
    category: "floristeria",
    region: "Gipuzkoa",
    province: "Gipuzkoa",
    city: "Donostia-San Sebastian",
    serviceArea: "Donostia-San Sebastian",
    phone: "943420658",
    email: "",
    website: "",
    contactUrl: "https://www.instagram.com/floristeriavillamarialuisa/",
    sourceUrl: "https://www.instagram.com/floristeriavillamarialuisa/",
    instagramUrl: "https://www.instagram.com/floristeriavillamarialuisa/",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Floristeria%20Villa%20Maria%20Luisa%20San%20Sebastian",
    capacity: 160,
    styleTags: ["floral", "clasico", "eventos", "decoracion"],
    languages: ["castellano"],
    availabilityType: "local",
    packages: [{ name: "ramos" }, { name: "decoracion bodas" }],
    priceFrom: 800,
    priceRange: "Consultar decoracion",
    priceConfidence: "baja",
    reliability: 8.1,
    responseTimeHours: 24,
    previousExperience: 6,
    qualityScore: 8.3,
    commissionFree: true,
    notes: "Floristeria historica de San Sebastian con trabajo en decoracion de bodas y eventos.",
    reviewsSummary: "Pendiente de contraste con resenas actuales.",
    notesInternal: "Validar disponibilidad de montaje de boda completa.",
    status: "reviewed",
    lastCheckedAt: "2026-07-06",
    lat: 43.318,
    lng: -1.981
  }
];

export const officialVendorPriceSeed: VendorPrice[] = [
  {
    id: "price-restaurante-arraiz-menu",
    vendorId: "vendor-restaurante-arraiz-bilbao",
    serviceName: "Menu de boda",
    season: "alta",
    region: "Bizkaia",
    minPrice: 165,
    maxPrice: 190,
    conditions: "Precio orientativo por persona; confirmar con proveedor.",
    historical: false
  },
  {
    id: "price-palacio-horkasitas-space",
    vendorId: "vendor-palacio-horkasitas-bizkaia",
    serviceName: "Alquiler de espacio",
    season: "alta",
    region: "Bizkaia",
    minPrice: 3000,
    maxPrice: 3200,
    conditions: "Precio orientativo de espacio; confirmar extras y proveedores obligatorios.",
    historical: false
  },
  {
    id: "price-mimiku-floral",
    vendorId: "vendor-mimiku-floristeria",
    serviceName: "Decoracion floral de boda",
    season: "alta",
    region: "Gipuzkoa",
    minPrice: 800,
    maxPrice: 1500,
    conditions: "Rango orientativo para boda; depende de piezas y montaje.",
    historical: false
  },
  {
    id: "price-gaizka-corta-reportaje",
    vendorId: "vendor-gaizka-corta-fotografia",
    serviceName: "Reportaje fotografico",
    season: "alta",
    region: "Gipuzkoa",
    minPrice: 1800,
    maxPrice: 2800,
    conditions: "Estimacion interna pendiente de propuesta oficial.",
    historical: false
  }
];
